- components/home/slack-events.js
Not tested, but this should whitelist channel names.
> Whitelist channel names

- pages/index.js
Was playing around with the opening animation and I think this feels better, particularly because it gives the video time to load.
> Slow down opening animation

- pages/index.js
Super small change - as of right now hackclub.com/community just redirects to the main page. Hopefully with an anchor it will automatically scroll down the the sign up form. I don't use React much so if this isn't the proper way to do it please lmk and I'll fix it.
> Add anchor to slack

- components/home/slack-events.js
Hours is a productivity channel! This is a super minor change, but I'm honestly doing it to see if I've got this whole forking and pull request thing. Is this how you do it?
> add #hours

- pages/api/join.js
- vercel.json
Sends new join requests to #invite-screener on Slack if the person is a student. If you click on "Invite User", it automatically invites the member to Slack (https://glitch.com/edit/#!/hackclub-invite-screener)
> Send new join request to Slack

- pages/index.js
> AMA schedule

- pages/index.js
this isn't a great solution, i can make a better one but this can work for now
> Launch Summer of Making

- pages/index.js
> Launch day has passed 

- components/slack/header.js
please verify manually, i dont have next on this machine
> Updated header.js to now have the z index correct

- pages/api/join.js
Don't merge yet, need to make some Clippy changes first
> Change default channel to #lobby

- .gitignore
- pages/api/channels/count-to-a-million.js
- pages/slack.js
I replaced the #confessions card with a #counttoamillion card that sort of displays the current number in the channel. (Doesn't automatically update, though.)
> Add #counttoamillion card

- pages/santa.js
Added Secret Santa page for 2020
> Secret Santa 2020 Page

- components/slack/slack-events.js
Add the following channels to the live slack feed:
1. go
2. ricing
3. gh
4. flutter
> ✨ Add a few more channels to the live slack feed

- components/preston-werner/amount.js
- components/preston-werner/copy.mdx
- pages/preston-werner.js
This is a working pull request for this gift announcement. I'll be working with @zachlatta here before we go live.
> Start Preston-Werner gift page

- pages/api/join.js
> Add IP logging

- pages/slack.js
we're up to 11,000+ Slack members now!
> Update Slack members from 10000+ to 11000+

- components/jobs/creative-director/jd.mdx
update text and add more details
> Do another pass of edits on Creative Director job description

- components/jobs/creative-director/jd.mdx
correct grammar and update text
> Do a pass of edits on Creative Director job description

- components/jobs/creative-director/jd.mdx
> add new description to Hack Club

- components/jobs/creative-director/jd.mdx
Did a line edit of the job description with team
> Do another pass of edits on the Creative Director JD

- components/jobs/creative-director/jd.mdx
Tweaked language so it might appeal to someone with a journalism background
> Update Creative Director job description

- components/jobs/creative-director/jd.mdx
Removed some of the description about Hack Club
> Trimmed down the word count

- components/jobs/creative-director/jd.mdx
> Update job description

- components/jobs/creative-director/jd.mdx
Move some of the extraneous paragraphs about the org to the bottom
> Shortened jd

- components/jobs/creative-director/jd.mdx
Changed title to Brand Director to better fit the role
> revised JD and changed title

- components/jobs/bank-ops-assistant/jd.mdx
- pages/jobs/bank-ops-assistant.js
> Add page for the Bank Ops Assistant job

- pages/minecraft.js
- Updated the link to the worldmap (vmc.hackclub.com/map -> mc.hackclub.com/map)
- Added a card for the modded server.
> Updated some info on the Minecraft page

- pages/index.js
> fixed typo on zephyr announcement

- pages/index.js
I believe the alt description should refer to the Elon Musk AMA
> updated alt description

- pages/404.js
- made text stick together
- made button appear on the next line
> made text stick together

- pages/index.js
Minor wording change. I think we should use "hackerland" instead of "hackerverse", because I think the idea of a "metaverse" has become somewhat corrupted.
> Hackerverse -> Hackerland

- pages/brand.js
The text on the navbar for the brands page blended in with the background of the entire website, so I changed the color to make it readable  I also noticed that the "Phantom Sans is our brand font" didn't have any spacing between them so I added that as well!
> Fix brand page
